from zingmp3py import ZingMp3, getUrlTypeAndID

getUrlTypeAndID("https://zingmp3.vn/liveradio/IWZ979CW.html")
zi = ZingMp3()
zi.getDetailPlaylist("67ZFO8DZ")
zi.getDetailArtist("Cammie")
zi.getRadioInfo("IWZ979CW")
zi.getSongInfo("ZWAF6UFD")
zi.getSongStreaming("ZWAF6UFD")
zi.getHomePage()
zi.getChartHome()
zi.getWeekChart("ZWAF6UFD")
zi.getNewReleaseChart()
zi.getTop100()
zi.search("rick roll")